# Generated by Django 5.2 on 2025-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1111111, max_length=128),
            preserve_default=False,
        ),
    ]
